name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends opam curl && opam init -y --bare --disable-sandboxing && pip3 install python-chess
    - name: Download and compile Stockfish
      working-directory: ./src
      run: make get-stockfish
    - name: Install Stockfish
      working-directory: ./src
      run: sudo make install-stockfish
    - name: Download and compile CHA
      working-directory: ./src
      run: make get-cha
    - name: Install CHA
      working-directory: ./src
      run: sudo make install-cha
    - name: Enable shared libraries
      run: sudo /sbin/ldconfig -v
    - name: Download and compile Sherlock
      working-directory: ./src/
      run: make get-sherlock
    - name: Compile Deadpos
      working-directory: ./src
      run: make
    - name: Test Vectors
      working-directory: ./src
      run: make test
    - name: Test PDB
      working-directory: ./src
      run: make pdb-tests